### PR TITLE
Fix .npmignore file

### PR DESCRIPTION
**Pull request by Pierre-Gilles**
## PR Description

Hi,

First, thank you for this awesome library! 

I installed it locally using NPM and realized that the module was taking **60Mb** on my disk. 

By looking at the folder structure, it seems that many folders (screenshots, documentation, .vscode, .github) are uploaded to NPM.

Here is the folder structure of the module uploaded to NPM:

screenshot 2019-02-05 at 09 12 57

So I checked the .npmignore, and indeed it was not working properly.

Here is a proposal of a fix in this PR.

Note: 

- I added the `coverage`, `test`, `.github` and `.vscode` folder. I don't think there are relevant when running the library.
- I added the `dist` folder to the .npmignore too, because it's a duplicate of the code and it seems that the package.json is calling `lib/index.js` as the main file, not the bundle one. Tell me if you think it's ok. 

## PR Checklist

This is a minor change not affecting tests :)

### CODE REVIEW

**Comment by jesus-seijas-sp** [comment]
Hello,
2 things:
- dist must not be avoided... is the browser version, so people can use nlp.js in frontend without node.
- coverage: I remember that last time I removed this, que quality of the package in npmjs got lower, I don't know how to tell npmjs the codecoverage without uploading this....

**Comment by Pierre-Gilles** [comment]
Hello,

- About dist, it means the library is included two times, `dist` + source file. Would it be possible to use the dist version for frontend use and Node.js use? If yes, it means we could only ship the dist folder! That would be awesome

- The quality of the package in npmjs? I don't think NPM knows something about code coverage.. never seen that. Where do you see that information?

**Comment by jesus-seijas-sp** [comment]
Hello @Pierre-Gilles 
About using the dist for frontend also for backend, no, two reasons:
1. The frontend version does not includes chinese
2. Having a backend library in node minimized is not a good practice when debugging

About npmjs quality: https://npms.io/about
In the section quality you've information.

**Comment by Pierre-Gilles** [comment]
Hey @jesus-seijas-sp,

Thanks for your answer.

1. Make sense! I added back the `dist` folder.

2. You could still use source-maps, but here for this tiny PR let's just put back the `dist` folder.

3. Thanks for this! I tried to read on the topic online, and it's not really clear how they calculate all that. 

It's possible to query the API to understand more your score ( ex: [https://api.npms.io/v2/package/node-nlp](https://api.npms.io/v2/package/node-nlp)

It's great because you can see all attributes that they use to score your package.

Like the size of the README, the size of the test folder, if your package has a npmignore file:

```
"files": {
   "readmeSize": 8711,
   "testsSize": 2118551,
   "hasNpmIgnore": true
},
```

The use a linter, if the project has good coverage and doesn't have outdated dependencies:

```
"linters": [
  "eslint", 
  "prettier"
],
"coverage": 0.95,
"outdatedDependencies": {
"brain.js": {
  "required": "1.6.0",
  "stable": "1.6.1",
  "latest": "1.6.1"
 }
}
``` 

So I putted back the `test` folder as well to ensure NPM can still calculate the test folder size. 

At least we removed screenshots & docs which were really taking lots of space :) 

Let me know if it's good to be merged for you, and have a nice day!

**Pull request merged**
