### PR TITLE
Saving for individual NLPClassifiers

### PR DESCRIPTION
**Pull request by Ishmaelk**
# Pull Request Template

## PR Checklist

- [ x] I have run `npm test` locally and all tests are passing.
- [x ] I have added/updated tests for any new behavior.
- [x ] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]

link to issue:
https://github.com/axa-group/nlp.js/issues/147

## PR Description
Edited nlp-classifier.js and nlp-classifier.test.js code to allow saving for individual classifiers. pass in a file name to NlpClassifier.save() and NlpClassifier.load() to persist and retrieve the state of an individual classifier that can exist outside of NlpManager.

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
Shame that v3 is such a huge rebase.

**Comment by jesus-seijas-sp** [comment]
@DiegoRBaquero This PR is code copy-pasted from the branch that I had for the v3, but time ago befor the v3 was finished.
The reasons for V3 is performance, both in time and score. In a real chatbot with 250 intents and 2500 utterances, the time to train was 38 minutes in my laptop, now is 36 seconds for the same model. 
You can check it with the console-bot example, in my laptop goes from 108 seconds to 3 seconds.
Also the size of the model.nlp is decreased from 1614KB down to 928KB.
And well, also the domains, now the domains are trained as separately neural networks, and there is a master neural network that instead of returning the intent returns the domain, so also this increase performance in time and score.

This PR will be deleted unless original code is commited.

**Comment by DiegoRBaquero** [comment]
@jesus-seijas-sp oh geez, that's great improvement!

Wondering, with `NlpClassifier` class gone, which one should be the go to? This doc is outdated now: https://github.com/axa-group/nlp.js/blob/master/docs/nlp-classifier.md

**Comment by jesus-seijas-sp** [comment]
@DiegoRBaquero Yes, my next task is update docs... nlp-classifier is not longer there. Basically the name was wrong, the correct name is nlu (Natural Language Understanding). Now in the folder nlu you have the different NLUs that can be used, based on the different classifiers. By default, the NlpManger uses the BrainNlu one. Also, now all classifiers and nlus have methods to export/import.

**Comment by DiegoRBaquero** [comment]
Perfect! Will look into migrating to v3 soon! Thank you!

**Comment by Ishmaelk** [comment]
I didn't mean to claim this code as original. For the purposes of out project we needed individual classifiers, not what is provided by managers or NER. It was incredibly inconvienent that classifiers couldn't be saved, that meant we would have to retrain each time we started our servers and I assumed this was a feature that other people wanted too so I just repurposed code in the NLPmanager for the classifier. We have what we need now so it doesn't matter much to us, and this pull request can be closed if the repo is going in a different direction.

**Comment by jesus-seijas-sp** [comment]
Well, you have v3.0.0 already published. Next step is to have a good documentation of the new classes and processes, and also an example of multi-domain training. But right now you can use the 3.0.0 in order to save classifiers and nlu.

**Comment by DiegoRBaquero** [comment]
This can be closed then, I guess. Thank you @Ishmaelk nonetheless

**Pull request closed without merging**
