### PR TITLE
Some minor improvements and a typo fix

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Comment by williamdes** [comment]
@jesus-seijas-sp My PR is ready for a review+merge

**Comment by williamdes** [comment]
https://github.com/axa-group/nlp.js/blob/0bc943299ef564ad302f7ddf37cf207ffbb5c8ca/lib/nlp/nlp-manager.js#L142 was removed with a changelog and broke my project..


But is still documented on https://github.com/axa-group/nlp.js/blob/v4.3.0/docs/v3/microsoft-bot-framework.md

Could you fix the example ?

**Comment by williamdes** [comment]
Also I had to do https://github.com/sudo-bot/gh-deployer/commit/4f4805337393291bd0492341ec20f8100d2177b1 in order to fix the tests, and had to comment the slot part

**Comment by jesus-seijas-sp** [comment]
thank you!

**Comment by williamdes** [comment]
Thank you merging my work
Could you have a look to my comment about the documentation examples?
I really need them to be fixed in order to know how to upgrade 😉

**Pull request merged**
