### PR TITLE
tests: Fix Build and testing

### PR DESCRIPTION
**Pull request by Apollon77**
# Pull Request Template

## PR Checklist

- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
- [x] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]

## PR Description

This PR does:
* update the package-locks to not reject packages from a non working artifactory server anymore (see https://github.com/axa-group/nlp.js/pull/1164#issuecomment-1198350962)
* update files with automatic prettifier results
* fix eslint errors
* add Node.js 16+18 to tests
* Fix unhandled promise rejections in tests (to have tests running in Node.js 16+)
* Correctly teardown the initialized Workers in tests for package "open-question"

Regarding the issues from sonarcloud ... seems they are in areas that I did not touched and mostly regex stuff where I'm not the expert

Additonally the commits are not "convenionally named". Sorry for that. Saw that too late and will change in future commits

### CODE REVIEW

**Comment by Apollon77** [comment]
@ericzon I would have 2-3 more PRs but I think it make sense to merge this one here (which "Just" fixes the CI testing and build" first. Do you think it is possible? Or tell me how to continue with my contributions

**Comment by eric-lara** [comment]
Hi @Apollon77 in which order do you prefer merging your PR's to reduce conflicts?

**Comment by Apollon77** [comment]
Let me check once the kids are in bed but when I remember correctly the PRs should work independently. But I have a look and confirm or comment the pr with order info. I comment here when done.

**Comment by Apollon77** [comment]
Ok, in fact they should not overlap that much, but I would do the following:

At first this PR to fix build and tests ... this is tthen ideal basis to run testing for each PR maybe again to proof that it is ok

After this then all PRs in order of creation (so #1164, then #1171, then #1172)

After that I have some more stuff prepared locally (which is mainly based on #1164 basically) that I would then split up into PRs and bring in next.

Bildschirm­foto 2022-11-24 um 21 52 35

This will be beside one fix mainly enhancements for Extractors and Entities (I need to find the relevant Issues these are for, but I added comments to them back in the days). It is mainly about to prevent the same text portions to be extracted multiple times by different extractors and to decide which is "best". It will e.g. prioritize "entities referenced in the relevant intent" higher then "other detected entities"

**Pull request merged**
